### ISSUE TITLE
Macでganttlogger --plotterでError

### ISSUE THREAD

**Issue by IkegamiAyano** [KagenoMoheji/GanttLogger#8] opened 2019-07-19 13:42 UTC
> Run, Plotter!
> Traceback (most recent call last):
>   File "/anaconda3/bin/ganttlogger", line 11, in <module>
>     sys.exit(main())
>   File "/anaconda3/lib/python3.6/site-packages/ganttlogger/app.py", line 42, in main
>     plotter.start()
>   File "/anaconda3/lib/python3.6/site-packages/ganttlogger/modules/Plotter.py", line 248, in start
>     self.run()
>   File "/anaconda3/lib/python3.6/site-packages/ganttlogger/modules/Plotter.py", line 328, in run
>     ax1.broken_barh(self.df_active_tab[k], (5+i*10, 5), facecolor="red")
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1855, in inner
>     return func(ax, *args, **kwargs)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 2543, in broken_barh
>     xranges = self.convert_xunits(xranges)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 191, in convert_xunits
>     return ax.xaxis.convert_units(x)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1526, in convert_units
>     ret = self.converter.convert(x, self.units, self)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/dates.py", line 1816, in convert
>     return date2num(value)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/dates.py", line 452, in date2num
>     return _to_ordinalf_np_vectorized(d)
>   File "/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2755, in __call__
>     return self._vectorize_call(func=func, args=vargs)
>   File "/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2831, in _vectorize_call
>     outputs = ufunc(*inputs)
>   File "/anaconda3/lib/python3.6/site-packages/matplotlib/dates.py", line 255, in _to_ordinalf
>     base = float(dt.toordinal())
> AttributeError: 'datetime.timedelta' object has no attribute 'toordinal' 
>

**Comment by KagenoMoheji** [comment] 2019-07-19 14:02
Duplicate of #1

**Closed** 2019-07-21 18:37 UTC
